#!/bin/bash

stringContains() { [ -z "${2##*$1*}" ]; }

if [[ -z "$1" ]]; then
  echo "no i2c number"
  exit;
fi

OUT=`ddccontrol -r 0x10 dev:/dev/i2c-${1} 2>/dev/null | grep -i Control  `

OUT=${OUT##*Control}

OUT=${OUT#*/}
BRIGHTNESS=${OUT%/*}

printf $BRIGHTNESS > $HOME/.cache/wayward-brightness
exit;

