/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */
 
#pragma once

#define BINDIR "/usr/bin"

#define DATADIR "/usr/share"

#define ENABLE_EGL 1


#define EGL_NO_X11 1

#define HAVE_INITGROUPS 1

#define HAVE_LINUX_SYNC_FILE_H 1

#define HAVE_MEMFD_CREATE 1

#define HAVE_MKOSTEMP 1

#define HAVE_POSIX_FALLOCATE 1

#define HAVE_STRCHRNUL 1

#define HAVE_XKBCOMMON_COMPOSE 1

#define LIBEXECDIR "/usr/lib"

#define LIBWESTON_MODULEDIR "/usr/lib/libweston-9"

#define MAJOR_IN_SYSMACROS 1

#define MESA_EGL_NO_X11_HEADERS 1

#define MODULEDIR "/usr/lib/weston"

#define PACKAGE_BUGREPORT ""

#define PACKAGE_STRING "weston 9.0.0"

#define PACKAGE_URL ""

#define PACKAGE_VERSION "9.0.0"

#define VERSION "9.0.0"

#define WESTON_NATIVE_BACKEND "drm-backend.so"

#define _ALL_SOURCE 1

#define _GNU_SOURCE 1

