/* Generated by wayland-scanner 1.19.0 */

#ifndef SHELL_HELPER_CLIENT_PROTOCOL_H
#define SHELL_HELPER_CLIENT_PROTOCOL_H

#include <stdint.h>
#include <stddef.h>
#include "wayland-client.h"

#ifdef  __cplusplus
extern "C" {
#endif

/**
 * @page page_shell_helper The shell_helper protocol
 * @section page_ifaces_shell_helper Interfaces
 * - @subpage page_iface_shell_helper - 
 */
struct shell_helper;
struct weston_desktop_shell;
struct wl_seat;
struct wl_surface;

#ifndef SHELL_HELPER_INTERFACE
#define SHELL_HELPER_INTERFACE
/**
 * @page page_iface_shell_helper shell_helper
 * @section page_iface_shell_helper_api API
 * See @ref iface_shell_helper.
 */
/**
 * @defgroup iface_shell_helper The shell_helper interface
 */
extern const struct wl_interface shell_helper_interface;
#endif

#define SHELL_HELPER_MOVE_SURFACE 0
#define SHELL_HELPER_ADD_SURFACE_TO_LAYER 1
#define SHELL_HELPER_SET_PANEL 2
#define SHELL_HELPER_SLIDE_SURFACE 3
#define SHELL_HELPER_CHANGE_GAMMA 4
#define SHELL_HELPER_BIND_KEY_PANEL 5
#define SHELL_HELPER_KEYBOARD_FOCUS_SURFACE 6
#define SHELL_HELPER_SLIDE_SURFACE_BACK 7
#define SHELL_HELPER_CURTAIN 8
#define SHELL_HELPER_LAUNCH_EXPOSAY 9
#define SHELL_HELPER_TOGGLE_INHIBIT 10
#define SHELL_HELPER_MOVE_BACKGROUND_SURFACE 11


/**
 * @ingroup iface_shell_helper
 */
#define SHELL_HELPER_MOVE_SURFACE_SINCE_VERSION 1
/**
 * @ingroup iface_shell_helper
 */
#define SHELL_HELPER_ADD_SURFACE_TO_LAYER_SINCE_VERSION 1
/**
 * @ingroup iface_shell_helper
 */
#define SHELL_HELPER_SET_PANEL_SINCE_VERSION 1
/**
 * @ingroup iface_shell_helper
 */
#define SHELL_HELPER_SLIDE_SURFACE_SINCE_VERSION 1
/**
 * @ingroup iface_shell_helper
 */
#define SHELL_HELPER_CHANGE_GAMMA_SINCE_VERSION 1
/**
 * @ingroup iface_shell_helper
 */
#define SHELL_HELPER_BIND_KEY_PANEL_SINCE_VERSION 1
/**
 * @ingroup iface_shell_helper
 */
#define SHELL_HELPER_KEYBOARD_FOCUS_SURFACE_SINCE_VERSION 1
/**
 * @ingroup iface_shell_helper
 */
#define SHELL_HELPER_SLIDE_SURFACE_BACK_SINCE_VERSION 1
/**
 * @ingroup iface_shell_helper
 */
#define SHELL_HELPER_CURTAIN_SINCE_VERSION 1
/**
 * @ingroup iface_shell_helper
 */
#define SHELL_HELPER_LAUNCH_EXPOSAY_SINCE_VERSION 1
/**
 * @ingroup iface_shell_helper
 */
#define SHELL_HELPER_TOGGLE_INHIBIT_SINCE_VERSION 1
/**
 * @ingroup iface_shell_helper
 */
#define SHELL_HELPER_MOVE_BACKGROUND_SURFACE_SINCE_VERSION 1

/** @ingroup iface_shell_helper */
static inline void
shell_helper_set_user_data(struct shell_helper *shell_helper, void *user_data)
{
	wl_proxy_set_user_data((struct wl_proxy *) shell_helper, user_data);
}

/** @ingroup iface_shell_helper */
static inline void *
shell_helper_get_user_data(struct shell_helper *shell_helper)
{
	return wl_proxy_get_user_data((struct wl_proxy *) shell_helper);
}

static inline uint32_t
shell_helper_get_version(struct shell_helper *shell_helper)
{
	return wl_proxy_get_version((struct wl_proxy *) shell_helper);
}

/** @ingroup iface_shell_helper */
static inline void
shell_helper_destroy(struct shell_helper *shell_helper)
{
	wl_proxy_destroy((struct wl_proxy *) shell_helper);
}

/**
 * @ingroup iface_shell_helper
 */
static inline void
shell_helper_move_surface(struct shell_helper *shell_helper, struct wl_surface *surface, int32_t x, int32_t y)
{
	wl_proxy_marshal((struct wl_proxy *) shell_helper,
			 SHELL_HELPER_MOVE_SURFACE, surface, x, y);
}

/**
 * @ingroup iface_shell_helper
 */
static inline void
shell_helper_add_surface_to_layer(struct shell_helper *shell_helper, struct wl_surface *new_surface, struct wl_surface *existing_surface)
{
	wl_proxy_marshal((struct wl_proxy *) shell_helper,
			 SHELL_HELPER_ADD_SURFACE_TO_LAYER, new_surface, existing_surface);
}

/**
 * @ingroup iface_shell_helper
 */
static inline void
shell_helper_set_panel(struct shell_helper *shell_helper, struct wl_surface *surface)
{
	wl_proxy_marshal((struct wl_proxy *) shell_helper,
			 SHELL_HELPER_SET_PANEL, surface);
}

/**
 * @ingroup iface_shell_helper
 */
static inline void
shell_helper_slide_surface(struct shell_helper *shell_helper, struct wl_surface *surface, int32_t x, int32_t y)
{
	wl_proxy_marshal((struct wl_proxy *) shell_helper,
			 SHELL_HELPER_SLIDE_SURFACE, surface, x, y);
}

/**
 * @ingroup iface_shell_helper
 */
static inline void
shell_helper_change_gamma(struct shell_helper *shell_helper, struct wl_surface *surface, int32_t reset)
{
	wl_proxy_marshal((struct wl_proxy *) shell_helper,
			 SHELL_HELPER_CHANGE_GAMMA, surface, reset);
}

/**
 * @ingroup iface_shell_helper
 */
static inline void
shell_helper_bind_key_panel(struct shell_helper *shell_helper, struct wl_surface *surface, struct wl_seat *seat, struct weston_desktop_shell *shell)
{
	wl_proxy_marshal((struct wl_proxy *) shell_helper,
			 SHELL_HELPER_BIND_KEY_PANEL, surface, seat, shell);
}

/**
 * @ingroup iface_shell_helper
 */
static inline void
shell_helper_keyboard_focus_surface(struct shell_helper *shell_helper, struct wl_surface *surface)
{
	wl_proxy_marshal((struct wl_proxy *) shell_helper,
			 SHELL_HELPER_KEYBOARD_FOCUS_SURFACE, surface);
}

/**
 * @ingroup iface_shell_helper
 */
static inline void
shell_helper_slide_surface_back(struct shell_helper *shell_helper, struct wl_surface *surface)
{
	wl_proxy_marshal((struct wl_proxy *) shell_helper,
			 SHELL_HELPER_SLIDE_SURFACE_BACK, surface);
}

/**
 * @ingroup iface_shell_helper
 */
static inline void
shell_helper_curtain(struct shell_helper *shell_helper, struct wl_surface *surface, int32_t show)
{
	wl_proxy_marshal((struct wl_proxy *) shell_helper,
			 SHELL_HELPER_CURTAIN, surface, show);
}

/**
 * @ingroup iface_shell_helper
 */
static inline void
shell_helper_launch_exposay(struct shell_helper *shell_helper, struct weston_desktop_shell *shell, struct wl_seat *seat)
{
	wl_proxy_marshal((struct wl_proxy *) shell_helper,
			 SHELL_HELPER_LAUNCH_EXPOSAY, shell, seat);
}

/**
 * @ingroup iface_shell_helper
 */
static inline void
shell_helper_toggle_inhibit(struct shell_helper *shell_helper, struct weston_desktop_shell *shell, struct wl_seat *seat)
{
	wl_proxy_marshal((struct wl_proxy *) shell_helper,
			 SHELL_HELPER_TOGGLE_INHIBIT, shell, seat);
}

/**
 * @ingroup iface_shell_helper
 */
static inline void
shell_helper_move_background_surface(struct shell_helper *shell_helper, struct weston_desktop_shell *shell, struct wl_surface *background_surface)
{
	wl_proxy_marshal((struct wl_proxy *) shell_helper,
			 SHELL_HELPER_MOVE_BACKGROUND_SURFACE, shell, background_surface);
}

#ifdef  __cplusplus
}
#endif

#endif
