/* Generated by wayland-scanner 1.19.0 */

#ifndef SHELL_HELPER_SERVER_PROTOCOL_H
#define SHELL_HELPER_SERVER_PROTOCOL_H

#include <stdint.h>
#include <stddef.h>
#include "wayland-server.h"

#ifdef  __cplusplus
extern "C" {
#endif

struct wl_client;
struct wl_resource;

/**
 * @page page_shell_helper The shell_helper protocol
 * @section page_ifaces_shell_helper Interfaces
 * - @subpage page_iface_shell_helper - 
 */
struct shell_helper;
struct weston_desktop_shell;
struct wl_seat;
struct wl_surface;

#ifndef SHELL_HELPER_INTERFACE
#define SHELL_HELPER_INTERFACE
/**
 * @page page_iface_shell_helper shell_helper
 * @section page_iface_shell_helper_api API
 * See @ref iface_shell_helper.
 */
/**
 * @defgroup iface_shell_helper The shell_helper interface
 */
extern const struct wl_interface shell_helper_interface;
#endif

/**
 * @ingroup iface_shell_helper
 * @struct shell_helper_interface
 */
struct shell_helper_interface {
	/**
	 */
	void (*move_surface)(struct wl_client *client,
			     struct wl_resource *resource,
			     struct wl_resource *surface,
			     int32_t x,
			     int32_t y);
	/**
	 */
	void (*add_surface_to_layer)(struct wl_client *client,
				     struct wl_resource *resource,
				     struct wl_resource *new_surface,
				     struct wl_resource *existing_surface);
	/**
	 */
	void (*set_panel)(struct wl_client *client,
			  struct wl_resource *resource,
			  struct wl_resource *surface);
	/**
	 */
	void (*slide_surface)(struct wl_client *client,
			      struct wl_resource *resource,
			      struct wl_resource *surface,
			      int32_t x,
			      int32_t y);
	/**
	 */
	void (*change_gamma)(struct wl_client *client,
			     struct wl_resource *resource,
			     struct wl_resource *surface,
			     int32_t reset);
	/**
	 */
	void (*bind_key_panel)(struct wl_client *client,
			       struct wl_resource *resource,
			       struct wl_resource *surface,
			       struct wl_resource *seat,
			       struct wl_resource *shell);
	/**
	 */
	void (*keyboard_focus_surface)(struct wl_client *client,
				       struct wl_resource *resource,
				       struct wl_resource *surface);
	/**
	 */
	void (*slide_surface_back)(struct wl_client *client,
				   struct wl_resource *resource,
				   struct wl_resource *surface);
	/**
	 */
	void (*curtain)(struct wl_client *client,
			struct wl_resource *resource,
			struct wl_resource *surface,
			int32_t show);
	/**
	 */
	void (*launch_exposay)(struct wl_client *client,
			       struct wl_resource *resource,
			       struct wl_resource *shell,
			       struct wl_resource *seat);
	/**
	 */
	void (*toggle_inhibit)(struct wl_client *client,
			       struct wl_resource *resource,
			       struct wl_resource *shell,
			       struct wl_resource *seat);
	/**
	 */
	void (*move_background_surface)(struct wl_client *client,
					struct wl_resource *resource,
					struct wl_resource *shell,
					struct wl_resource *background_surface);
};


/**
 * @ingroup iface_shell_helper
 */
#define SHELL_HELPER_MOVE_SURFACE_SINCE_VERSION 1
/**
 * @ingroup iface_shell_helper
 */
#define SHELL_HELPER_ADD_SURFACE_TO_LAYER_SINCE_VERSION 1
/**
 * @ingroup iface_shell_helper
 */
#define SHELL_HELPER_SET_PANEL_SINCE_VERSION 1
/**
 * @ingroup iface_shell_helper
 */
#define SHELL_HELPER_SLIDE_SURFACE_SINCE_VERSION 1
/**
 * @ingroup iface_shell_helper
 */
#define SHELL_HELPER_CHANGE_GAMMA_SINCE_VERSION 1
/**
 * @ingroup iface_shell_helper
 */
#define SHELL_HELPER_BIND_KEY_PANEL_SINCE_VERSION 1
/**
 * @ingroup iface_shell_helper
 */
#define SHELL_HELPER_KEYBOARD_FOCUS_SURFACE_SINCE_VERSION 1
/**
 * @ingroup iface_shell_helper
 */
#define SHELL_HELPER_SLIDE_SURFACE_BACK_SINCE_VERSION 1
/**
 * @ingroup iface_shell_helper
 */
#define SHELL_HELPER_CURTAIN_SINCE_VERSION 1
/**
 * @ingroup iface_shell_helper
 */
#define SHELL_HELPER_LAUNCH_EXPOSAY_SINCE_VERSION 1
/**
 * @ingroup iface_shell_helper
 */
#define SHELL_HELPER_TOGGLE_INHIBIT_SINCE_VERSION 1
/**
 * @ingroup iface_shell_helper
 */
#define SHELL_HELPER_MOVE_BACKGROUND_SURFACE_SINCE_VERSION 1

#ifdef  __cplusplus
}
#endif

#endif
